
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteHospital.Core
{

using System;
    using System.Collections.Generic;
    
public partial class ContactU
{

    public int Id { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string WorkingHours { get; set; }

    public string Location { get; set; }

    public string AddressMob { get; set; }

    public string WorkingHoursMob { get; set; }

    public string AddressArabicMob { get; set; }

    public string WorkingHoursArabicMob { get; set; }

}

}
