

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteHospital.Core
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EliteHospitalEntities : DbContext
{
    public EliteHospitalEntities()
        : base("name=EliteHospitalEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<PatientVerification> PatientVerifications { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<CovidBanner> CovidBanners { get; set; }

    public virtual DbSet<Career> Careers { get; set; }

    public virtual DbSet<Banner> Banners { get; set; }

    public virtual DbSet<HomeBanner> HomeBanners { get; set; }

    public virtual DbSet<AboutU> AboutUS { get; set; }

    public virtual DbSet<DailyOffer> DailyOffers { get; set; }

    public virtual DbSet<Insurance> Insurances { get; set; }

    public virtual DbSet<SpecialOffer> SpecialOffers { get; set; }

    public virtual DbSet<OnlineConsultation> OnlineConsultations { get; set; }

    public virtual DbSet<VideoUrl> VideoUrls { get; set; }

    public virtual DbSet<Doctor> Doctors { get; set; }

    public virtual DbSet<ContactU> ContactUs { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventImage> EventImages { get; set; }

    public virtual DbSet<tbl_CommonParameter> tbl_CommonParameter { get; set; }

    public virtual DbSet<tbl_PatientMaster> tbl_PatientMaster { get; set; }

    public virtual DbSet<tbl_ServiceMaster> tbl_ServiceMaster { get; set; }

    public virtual DbSet<tbl_TransactionHistory> tbl_TransactionHistory { get; set; }

}

}

