
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteHospital.Core
{

using System;
    using System.Collections.Generic;
    
public partial class OnlineConsultation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OnlineConsultation()
    {

        this.VideoUrls = new HashSet<VideoUrl>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public byte[] Image { get; set; }

    public string Path { get; set; }

    public string Url { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VideoUrl> VideoUrls { get; set; }

}

}
