
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteHospital.Core
{

using System;
    using System.Collections.Generic;
    
public partial class PatientVerification
{

    public int Id { get; set; }

    public string MobileNo { get; set; }

    public Nullable<int> VerificationCode { get; set; }

    public Nullable<System.DateTime> ExpiringOnUTC { get; set; }

    public int RetryAttempts { get; set; }

    public System.DateTime CreatedOnUTC { get; set; }

    public Nullable<System.DateTime> LastVerifiedOnUTC { get; set; }

}

}
