
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteHospital.Core
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_TransactionHistory
{

    public int TH_Id { get; set; }

    public Nullable<int> TH_PM_Id { get; set; }

    public Nullable<decimal> TH_PurchasedAmount { get; set; }

    public Nullable<decimal> TH_LoyaltyPoints { get; set; }

    public Nullable<decimal> TH_QtrAmount { get; set; }

    public Nullable<System.DateTime> TH_AddedDate { get; set; }

    public Nullable<decimal> TH_RedeemPoints { get; set; }

    public Nullable<System.DateTime> TH_RedeemedDate { get; set; }

    public string TH_Narrations { get; set; }

    public string TH_Status { get; set; }

    public Nullable<decimal> TH_BalancePoints { get; set; }

    public string TH_ServiceId { get; set; }

    public string TH_Promocode { get; set; }

}

}
