//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string BannerTitle { get; set; }
        public string BannerTitleArabic { get; set; }
        public string BannerSubTitle { get; set; }
        public string BannerSubTitleArabic { get; set; }
        public byte[] BannerImage { get; set; }
        public string BannerImagePath { get; set; }
        public byte[] BannerImageMobile { get; set; }
        public string BannerImageMobilePath { get; set; }
        public string DepartmentName { get; set; }
        public string Banner_Image { get; set; }
    }
}
