//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigPasswords
    {
        public int ID { get; set; }
        public string ConfigPasswordName { get; set; }
        public string ConfigPassValues { get; set; }
    }
}
