//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public long DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNameArabic { get; set; }
        public string Description { get; set; }
        public string DescriptionArabic { get; set; }
        public string LongDescription { get; set; }
        public byte[] DepartmentImage { get; set; }
        public string DepartmentImagePath { get; set; }
        public byte[] DepartmentImageMob { get; set; }
        public string DepartmentImageMobPath { get; set; }
        public string Status { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public byte[] DepartmentIconImage { get; set; }
        public string DepartmentIconImagePath { get; set; }
        public string Department_Image { get; set; }
        public string Department_Icon { get; set; }
        public string Department_Type { get; set; }
    }
}
