//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int Id { get; set; }
        public string DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string DoctorNameArabic { get; set; }
        public byte[] DoctorImage { get; set; }
        public string DoctorImagePath { get; set; }
        public byte[] DoctorImageMob { get; set; }
        public string DoctorImageMobPath { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Status { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string DoctorDescription { get; set; }
        public string DoctorBioStatus { get; set; }
        public string Doctor_Image { get; set; }
        public string DepartmentName { get; set; }
        public string Position { get; set; }
        public string DoctorDescription_Arabic { get; set; }
    }
}
