//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceMaster
    {
        public int SM_Id { get; set; }
        public string SM_Name { get; set; }
        public string SM_Points { get; set; }
        public Nullable<System.DateTime> SM_CreatedDate { get; set; }
        public Nullable<System.DateTime> SM_LastUpdatedDate { get; set; }
        public string SM_Name_Arabic { get; set; }
    }
}
