//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PatientMaster
    {
        public int PM_Id { get; set; }
        public string PM_FistName { get; set; }
        public string PM_LastName { get; set; }
        public Nullable<System.DateTime> PM_DOB { get; set; }
        public string PM_Genter { get; set; }
        public string PM_Email { get; set; }
        public string PM_Mobile { get; set; }
        public string PM_QID { get; set; }
        public Nullable<System.DateTime> PM_CreatedDate { get; set; }
        public Nullable<System.DateTime> PM_LastUpdatedDate { get; set; }
        public Nullable<decimal> PM_Price { get; set; }
        public string PM_ServiceId { get; set; }
        public string PM_Promocode { get; set; }
        public Nullable<int> PM_VerificationCode { get; set; }
        public Nullable<int> PM_ServerPatientId { get; set; }
    }
}
