//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteHospital.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoUrl
    {
        public int Id { get; set; }
        public int OnlineConsultationId { get; set; }
        public string VideoUrls { get; set; }
        public string Description { get; set; }
    
        public virtual OnlineConsultation OnlineConsultation { get; set; }
    }
}
